name: Scheduled Run

on:
  schedule:
    - cron: '40 3,9 * * *'  # UTC 时间为上海时间的中午 11:40 和晚上 5:40
  workflow_dispatch:  # 添加这行

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai  # 安装 openai 库

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python action.py
